name: Re-archive the templates

on:
  push:
    branches: [develop]

jobs:
  # delete_the_current_artifacts:
  build_the_current__artifacts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps: 
      - uses: actions/checkout@v3

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y.%m.%d-T%H.%M.%S')"    

      - name: version
        run: echo "::set-output name=version::${{ steps.timestamp.outputs.timestamp }}"
        id: version          

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Build artefact for 'client'
        uses: actions/upload-artifact@v3
        with:
          name: client-${{ steps.timestamp.outputs.timestamp }}
          path: templates/client          
          
      - name: Build artefact for 'server'
        uses: actions/upload-artifact@v3
        with:
          name: server-${{ steps.timestamp.outputs.timestamp }}
          path: templates/server           
          
      - name: Build artefact for 'mobile'
        uses: actions/upload-artifact@v3
        with:
          name: mobile-${{ steps.timestamp.outputs.timestamp }}
          path: templates/mobile 

    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
          
  release_the_current__artifacts:
    permissions: write-all
    name: Release artifacts
    needs: build_the_current__artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          artifacts: "client-${{ steps.timestamp.outputs.timestamp }}.zip, server-${{ steps.timestamp.outputs.timestamp }}.zip, mobile-${{ steps.timestamp.outputs.timestamp }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          tag: "${GITHUB_REF##*/}"
          #body_path: CHANGELOG.md
          
      - name: debug
        run: |
          echo  "-----------${GITHUB_REF##*/}------------"

#       - name: upload client artifact
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./client-${{ steps.timestamp.outputs.timestamp }}
#           asset_name: client-${{ steps.timestamp.outputs.timestamp }}
#           asset_content_type: application/gzip    

#       - name: upload server artifact
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./server-${{ steps.timestamp.outputs.timestamp }}
#           asset_name: server-${{ steps.timestamp.outputs.timestamp }}
#           asset_content_type: application/gzip              

#       - name: upload mobile artifact
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./mobile-${{ steps.timestamp.outputs.timestamp }}
#           asset_name: mobile-${{ steps.timestamp.outputs.timestamp }}
#           asset_content_type: application/gzip              
