name: Re-archive the templates

on:
  push:
    branches: [develop]

jobs:
  # delete_the_current_artifacts:
  generate_the_current__artifacts:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps: 
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Remove and generate new archive for 'client' template
        run: |
          cd templates/client
          find . -type f -name "client.zip" -delete
          
      - name: Archive for 'client'
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: templates/client          

      - name: Remove and generate new archive for 'server' template
        run: |
          cd templates/server
          find . -type f -name "server.zip" -delete
          
      - name: Archive for 'server'
        uses: actions/upload-artifact@v3
        with:
          name: server
          path: templates/server           

      - name: Remove and generate new archive for 'mobile' template
        run: |
          cd templates/mobile
          find . -type f -name "mobile.zip" -delete
          
      - name: Archive for 'mobile'
        uses: actions/upload-artifact@v3
        with:
          name: mobile
          path: templates/mobile          
